[package]
name = "ipi-game"
version = "0.1.0"
authors = ["Abdun Nihaal"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.67"
wee_alloc = "0.4.5"

[profile.release]
lto = true
opt-level = 's'
